meta:
  version: 2
  flow: Classic
  substituting_steps:
    # IO pads are used instead of pins
    OpenROAD.IOPlacement: null
    +Odb.SetPowerConnections: OpenROAD.Padring
    
    # Add Seal Ring
    +Checker.XOR: KLayout.SealRing
    
    # Run Filler insertion
    #+KLayout.SealRing: KLayout.FillerGeneration

    # Magic reports some overlaps which can be ignored
    Checker.IllegalOverlap: null

    # Save time
    KLayout.DRC: null
    Magic.DRC: null

    #Odb.ReportDisconnectedPins: null # TODO IOs

    Magic.WriteLEF: null # Not needed, save time
    Odb.CheckDesignAntennaProperties: null # Requires LEF

    # Add steps for LVS with KLayout
    #+Checker.LVS: OpenROAD.WriteCDL
    #+OpenROAD.WriteCDL: KLayout.LVS

DESIGN_NAME: heichips25_top
VERILOG_FILES:
- dir::src/heichips25_top.v
- dir::src/heichips25_core.sv
- dir::ip/fabric/rtl/fabric_wrapper.sv
- dir::ip/fabric_config/fabric_config.sv
- dir::ip/fabric_config/fabric_spi_controller.sv
- dir::ip/fabric_config/fabric_spi_receiver.sv

# SRAMs require FUNCTIONAL
VERILOG_DEFINES:
- FUNCTIONAL

PRIMARY_GDSII_STREAMOUT_TOOL: klayout
#MAGIC_EXT_USE_GDS: true

# Use minimal DRC rules
#KLAYOUT_DRC_RUNSET: pdk_dir::/libs.tech/klayout/tech/drc/sg13g2_minimal.lydrc

KLAYOUT_DRC_OPTIONS:
  densityRules: true

EXTRA_GDS:
- dir::ip/bondpad/bondpad_70x70.gds

EXTRA_LEFS:
- dir::ip/bondpad/bondpad_70x70.lef

PAD_SOUTH: [
    "sg13g2_IOPadInOut30mA_fpga_io\\[16\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[17\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[18\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[19\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[20\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[21\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[22\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[23\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[24\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[25\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[26\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[27\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[28\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[29\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[30\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[31\\].fpga_io"
]

PAD_EAST: [
    sg13g2_IOPadIOVdd_east,
    sg13g2_IOPadIOVss_east,
        
    sg13g2_IOPadOut30mA_fpga_config_busy,
    sg13g2_IOPadOut30mA_fpga_config_configured,
    
    "sg13g2_IOPadAnalog_analog\\[0\\].analog",
    "sg13g2_IOPadAnalog_analog\\[1\\].analog",
    "sg13g2_IOPadAnalog_analog\\[2\\].analog",
    "sg13g2_IOPadAnalog_analog\\[3\\].analog",
    "sg13g2_IOPadAnalog_analog\\[4\\].analog",
    "sg13g2_IOPadAnalog_analog\\[5\\].analog",
    "sg13g2_IOPadAnalog_analog\\[6\\].analog",
    "sg13g2_IOPadAnalog_analog\\[7\\].analog",
    "sg13g2_IOPadAnalog_analog\\[8\\].analog",
    "sg13g2_IOPadAnalog_analog\\[9\\].analog",

    sg13g2_IOPadVss_east,
    sg13g2_IOPadVdd_east
]

PAD_NORTH: [
    "sg13g2_IOPadInOut30mA_fpga_io\\[0\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[1\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[2\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[3\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[4\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[5\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[6\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[7\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[8\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[9\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[10\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[11\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[12\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[13\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[14\\].fpga_io",
    "sg13g2_IOPadInOut30mA_fpga_io\\[15\\].fpga_io"
]

PAD_WEST: [
    sg13g2_IOPadVdd_west,
    sg13g2_IOPadVss_west,

    sg13g2_IOPadIn_fpga_clk,
    sg13g2_IOPadIn_fpga_rst_n,
    
    sg13g2_IOPadInOut30mA_fpga_sclk,
    sg13g2_IOPadInOut30mA_fpga_cs_n,
    sg13g2_IOPadInOut30mA_fpga_mosi,
    sg13g2_IOPadInOut30mA_fpga_miso,
    
    sg13g2_IOPadIn_fpga_mode,

    "sg13g2_IOPadIn_fpga_config_slot\\[0\\].fpga_config_slot",
    "sg13g2_IOPadIn_fpga_config_slot\\[1\\].fpga_config_slot",
    "sg13g2_IOPadIn_fpga_config_slot\\[2\\].fpga_config_slot",
    "sg13g2_IOPadIn_fpga_config_slot\\[3\\].fpga_config_slot",
    sg13g2_IOPadIn_fpga_config_trigger,
    
    sg13g2_IOPadIOVss_west,
    sg13g2_IOPadIOVdd_west
]

PNR_SDC_FILE: dir::constraint.sdc
SIGNOFF_SDC_FILE: dir::constraint.sdc
FALLBACK_SDC: dir::constraint.sdc

VDD_NETS:
- VDD
GND_NETS:
- VSS

GRT_ALLOW_CONGESTION: true

IGNORE_DISCONNECTED_MODULES:
- sg13g2_IOPadIn
- sg13g2_IOPadVdd
- sg13g2_IOPadVss
- sg13g2_IOPadInOut32mA
- sg13g2_IOPadOut32mA
- sg13g2_IOPadIOVss
- sg13g2_IOPadIOVdd

CLOCK_PORT: clock
CLOCK_PERIOD: 100
FP_SIZING: absolute
DIE_AREA: [0, 0, 3001, 2600]
CORE_AREA: [345, 345, 2655, 2255]
PL_TARGET_DENSITY_PCT: 50

# Power Distribution Network
PDN_CFG: dir::pdn.tcl
PDN_CORE_RING: True
PDN_CORE_RING_VWIDTH: 8.0
PDN_CORE_RING_HWIDTH: 8.0
PDN_CORE_RING_CONNECT_TO_PADS: True
PDN_ENABLE_PINS: False

# Because we have mutiple power
# pads for one power domain
MAGIC_EXT_UNIQUE: notopports

MACROS:
  eFPGA:
    gds:
      - dir::ip/fabric/macro/ihp-sg13g2/gds/eFPGA.gds
    lef:
      - dir::ip/fabric/macro/ihp-sg13g2/lef/eFPGA.lef
    nl:
      - dir::ip/fabric/macro/ihp-sg13g2/nl/eFPGA.nl.v
    spef:
      "nom_*":
        - dir::ip/fabric/macro/ihp-sg13g2/spef/nom/eFPGA.nom.spef
    instances: 
      heichips25_core.fabric_wrapper.eFPGA:
        # X should be multiple of 0.48 (Metal2 pitch)
        # Y should be multiple of 0.42 (Metal3 pitch)
        location: [974.88, 381.36]
        orientation: N
  RM_IHPSG13_1P_512x32_c2_bm_bist:
    gds:
      #- pdk_dir::libs.ref/sg13g2_sram/gds/RM_IHPSG13_1P_512x32_c2_bm_bist.gds
      - dir::tmp/RM_IHPSG13_1P_512x32_c2_bm_bist.gds
    lef:
      - pdk_dir::libs.ref/sg13g2_sram/lef/RM_IHPSG13_1P_512x32_c2_bm_bist.lef
    nl:
      - pdk_dir::libs.ref/sg13g2_sram/verilog/RM_IHPSG13_1P_512x32_c2_bm_bist.v
    lib:
      "nom_typ_1p20V_25C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_512x32_c2_bm_bist_typ_1p20V_25C.lib
      "nom_fast_1p32V_m40C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_512x32_c2_bm_bist_fast_1p32V_m55C.lib
      "nom_slow_1p08V_125C":
        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_512x32_c2_bm_bist_slow_1p08V_125C.lib
    instances:
      heichips25_core.fabric_wrapper.sram0_0:
        location: [2150, 1750]
        orientation: S
      heichips25_core.fabric_wrapper.sram0_1:
        location: [2150, 2020]
        orientation: N
  heichips25_example_small:
    gds:
      - dir::ip/user_projects/heichips25_example_small/macro/gds/heichips25_example_small.gds
    lef:
      - dir::ip/user_projects/heichips25_example_small/macro/lef/heichips25_example_small.lef
    nl:
      - dir::ip/user_projects/heichips25_example_small/macro/nl/heichips25_example_small.nl.v
    spef:
      "nom_*":
        - dir::ip/user_projects/heichips25_example_small/macro/spef/nom/heichips25_example_small.nom.spef
    instances:
      #heichips25_core.fabric_wrapper.heichips25_example_small_0:
      #  location: [388, 1540]
      #  orientation: FN
      #heichips25_core.fabric_wrapper.heichips25_example_small_1:
      #  location: [388, 1325]
      #  orientation: FN
      #heichips25_core.fabric_wrapper.heichips25_example_small_2:
      #  location: [388, 1110]
      #  orientation: FN
      #heichips25_core.fabric_wrapper.heichips25_example_small_3:
      #  location: [388, 895]
      #  orientation: FN
      heichips25_core.fabric_wrapper.heichips25_example_small_4:
        location: [388, 680]
        orientation: FN
      heichips25_core.fabric_wrapper.heichips25_example_small_5:
        location: [388, 465]
        orientation: FN

      #heichips25_core.fabric_wrapper.heichips25_example_small_6:
      #  location: [2109, 1110]
      #  orientation: N
      #heichips25_core.fabric_wrapper.heichips25_example_small_7:
      #  location: [2109, 895]
      #  orientation: N
      heichips25_core.fabric_wrapper.heichips25_example_small_8:
        location: [2109, 680]
        orientation: N
      heichips25_core.fabric_wrapper.heichips25_example_small_9:
        location: [2109, 465]
        orientation: N

  heichips25_example_large:
    gds:
      - dir::ip/user_projects/heichips25_example_large/macro/gds/heichips25_example_large.gds
    lef:
      - dir::ip/user_projects/heichips25_example_large/macro/lef/heichips25_example_large.lef
    nl:
      - dir::ip/user_projects/heichips25_example_large/macro/nl/heichips25_example_large.nl.v
    spef:
      "nom_*":
        - dir::ip/user_projects/heichips25_example_large/macro/spef/nom/heichips25_example_large.nom.spef
    #instances:
      #heichips25_core.fabric_wrapper.heichips25_example_large_0:
      #  location: [388, 1755]
      #  orientation: FN
      #heichips25_core.fabric_wrapper.heichips25_example_large_1:
      #  location: [2109, 1325]
      #  orientation: N

  heichips25_snitch_wrapper:
    gds:
      - dir::ip/user_projects/heichips_25_snitch_core/macro/gds/heichips25_snitch_wrapper.gds
    lef:
      - dir::ip/user_projects/heichips_25_snitch_core/macro/lef/heichips25_snitch_wrapper.lef
    nl:
      - dir::ip/user_projects/heichips_25_snitch_core/macro/nl/heichips25_snitch_wrapper.nl.v
    spef:
      "nom_*":
        - dir::ip/user_projects/heichips_25_snitch_core/macro/spef/nom/heichips25_snitch_wrapper.nom.spef
    instances:
      heichips25_core.fabric_wrapper.heichips25_example_large_0:
        location: [388, 1755]
        orientation: FN
      #heichips25_core.fabric_wrapper.heichips25_example_large_1:
      #  location: [2109, 1325]
      #  orientation: N

  heichips25_fazyrv_exotiny:
    gds:
      - dir::ip/user_projects/heichips25-fazyrv-exotiny/macro/gds/heichips25_fazyrv_exotiny.gds
    lef:
      - dir::ip/user_projects/heichips25-fazyrv-exotiny/macro/lef/heichips25_fazyrv_exotiny.lef
    nl:
      - dir::ip/user_projects/heichips25-fazyrv-exotiny/macro/nl/heichips25_fazyrv_exotiny.nl.v
    spef:
      "nom_*":
        - dir::ip/user_projects/heichips25-fazyrv-exotiny/macro/spef/nom/heichips25_fazyrv_exotiny.nom.spef
    instances:
      heichips25_core.fabric_wrapper.heichips25_example_large_1:
        location: [2109, 1325]
        orientation: N

  heichips25_CORDIC:
    gds:
      - dir::ip/user_projects/heichips25_CORDIC/macro/gds/heichips25_CORDIC.gds
    lef:
      - dir::ip/user_projects/heichips25_CORDIC/macro/lef/heichips25_CORDIC.lef
    nl:
      - dir::ip/user_projects/heichips25_CORDIC/macro/nl/heichips25_CORDIC.nl.v
    spef:
      "nom_*":
        - dir::ip/user_projects/heichips25_CORDIC/macro/spef/nom/heichips25_CORDIC.nom.spef
    instances:
      heichips25_core.fabric_wrapper.heichips25_example_small_0:
        location: [388, 1540]
        orientation: FN

  heichips25_sap3:
    gds:
      - dir::ip/user_projects/heiChips2025_sap3_and_sorter/heichips25_sap-3/macro/gds/heichips25_sap3.gds
    lef:
      - dir::ip/user_projects/heiChips2025_sap3_and_sorter/heichips25_sap-3/macro/lef/heichips25_sap3.lef
    nl:
      - dir::ip/user_projects/heiChips2025_sap3_and_sorter/heichips25_sap-3/macro/nl/heichips25_sap3.nl.v
    spef:
      "nom_*":
        - dir::ip/user_projects/heiChips2025_sap3_and_sorter/heichips25_sap-3/macro/spef/nom/heichips25_sap3.nom.spef
    instances:
      heichips25_core.fabric_wrapper.heichips25_example_small_1:
        location: [388, 1325]
        orientation: FN

  heichips25_top_sorter:
    gds:
      - dir::ip/user_projects/heiChips2025_sap3_and_sorter/heichips25_top_sorter/macro/gds/heichips25_top_sorter.gds
    lef:
      - dir::ip/user_projects/heiChips2025_sap3_and_sorter/heichips25_top_sorter/macro/lef/heichips25_top_sorter.lef
    nl:
      - dir::ip/user_projects/heiChips2025_sap3_and_sorter/heichips25_top_sorter/macro/nl/heichips25_top_sorter.nl.v
    spef:
      "nom_*":
        - dir::ip/user_projects/heiChips2025_sap3_and_sorter/heichips25_top_sorter/macro/spef/nom/heichips25_top_sorter.nom.spef
    instances:
      heichips25_core.fabric_wrapper.heichips25_example_small_2:
        location: [388, 1110]
        orientation: FN

  heichips25_systolicArrayTop:
    gds:
      - dir::ip/user_projects/heichips25_systolicArray4x4/macro/gds/heichips25_systolicArrayTop.gds
    lef:
      - dir::ip/user_projects/heichips25_systolicArray4x4/macro/lef/heichips25_systolicArrayTop.lef
    nl:
      - dir::ip/user_projects/heichips25_systolicArray4x4/macro/nl/heichips25_systolicArrayTop.nl.v
    spef:
      "nom_*":
        - dir::ip/user_projects/heichips25_systolicArray4x4/macro/spef/nom/heichips25_systolicArrayTop.nom.spef
    instances:
      heichips25_core.fabric_wrapper.heichips25_example_small_3:
        location: [388, 895]
        orientation: FN

  heichips25_bagel:
    gds:
      - dir::ip/user_projects/heichips25_bagel/macro/gds/heichips25_bagel.gds
    lef:
      - dir::ip/user_projects/heichips25_bagel/macro/lef/heichips25_bagel.lef
    nl:
      - dir::ip/user_projects/heichips25_bagel/macro/nl/heichips25_bagel.nl.v
    spef:
      "nom_*":
        - dir::ip/user_projects/heichips25_bagel/macro/spef/nom/heichips25_bagel.nom.spef
    instances:
      heichips25_core.fabric_wrapper.heichips25_example_small_6:
        location: [2109, 1110]
        orientation: N

  heichips25_usb_cdc:
    gds:
      - dir::ip/user_projects/heichips25-usb_cdc/macro/gds/heichips25_usb_cdc.gds
    lef:
      - dir::ip/user_projects/heichips25-usb_cdc/macro/lef/heichips25_usb_cdc.lef
    nl:
      - dir::ip/user_projects/heichips25-usb_cdc/macro/nl/heichips25_usb_cdc.nl.v
    spef:
      "nom_*":
        - dir::ip/user_projects/heichips25-usb_cdc/macro/spef/nom/heichips25_usb_cdc.nom.spef
    instances:
      heichips25_core.fabric_wrapper.heichips25_example_small_7:
        location: [2109, 895]
        orientation: N

PDN_OBSTRUCTIONS:
 # Left
 - [TopMetal1,  388, 1755,  888, 2170] # heichips25_example_large_0
 - [TopMetal1,  388, 1540,  888, 1740] # heichips25_example_small_0
 - [TopMetal1,  388, 1325,  888, 1525] # heichips25_example_small_1
 - [TopMetal1,  388, 1110,  888, 1310] # heichips25_example_small_2
 - [TopMetal1,  388, 895,   888, 1095] # heichips25_example_small_3
  
 # Right
 - [TopMetal1, 2109, 1325, 2609, 1740] # heichips25_example_large_1
 - [TopMetal2, 2517, 1333, 2572, 1385] # heichips25_example_large_1 logo window
 - [TopMetal1, 2109, 1110, 2609, 1310] # heichips25_example_small_6
 - [TopMetal1, 2109,  895, 2609, 1095] # heichips25_example_small_7
 
ROUTING_OBSTRUCTIONS:
 # Left
 - [TopMetal1,  388, 1755,  888, 2170] # heichips25_example_large_0
 - [TopMetal1,  388, 1540,  888, 1740] # heichips25_example_small_0
 - [TopMetal1,  388, 1325,  888, 1525] # heichips25_example_small_1
 - [TopMetal1,  388, 1110,  888, 1310] # heichips25_example_small_2
 
 # Right
 - [TopMetal1, 2109, 1325, 2609, 1740] # heichips25_example_large_1
 - [TopMetal2, 2517, 1333, 2572, 1385] # heichips25_example_large_1 logo window
 - [TopMetal1, 2109, 1110, 2609, 1310] # heichips25_example_small_6
 - [TopMetal1, 2109,  895, 2609, 1095] # heichips25_example_small_7
 
# TODO update pdn config
PDN_MACRO_CONNECTIONS:
  # eFPGA
  - "heichips25_core.fabric_wrapper.eFPGA VDD VSS VPWR VGND" 
  # Large User Projects
  - "heichips25_core.fabric_wrapper.heichips25_example_large_0 VDD VSS VPWR VGND"
  - "heichips25_core.fabric_wrapper.heichips25_example_large_1 VDD VSS VPWR VGND"
  # Small User Projects
  - "heichips25_core.fabric_wrapper.heichips25_example_small_0 VDD VSS VPWR VGND"
  - "heichips25_core.fabric_wrapper.heichips25_example_small_1 VDD VSS VPWR VGND"
  - "heichips25_core.fabric_wrapper.heichips25_example_small_2 VDD VSS VPWR VGND"
  - "heichips25_core.fabric_wrapper.heichips25_example_small_3 VDD VSS VPWR VGND"
  - "heichips25_core.fabric_wrapper.heichips25_example_small_4 VDD VSS VPWR VGND"
  - "heichips25_core.fabric_wrapper.heichips25_example_small_5 VDD VSS VPWR VGND"
  - "heichips25_core.fabric_wrapper.heichips25_example_small_6 VDD VSS VPWR VGND"
  - "heichips25_core.fabric_wrapper.heichips25_example_small_7 VDD VSS VPWR VGND"
  - "heichips25_core.fabric_wrapper.heichips25_example_small_8 VDD VSS VPWR VGND"
  - "heichips25_core.fabric_wrapper.heichips25_example_small_9 VDD VSS VPWR VGND"
  # SRAM
  - "heichips25_core.fabric_wrapper.sram0_0 VDD VSS VDD! VSS!"
  - "heichips25_core.fabric_wrapper.sram0_0 VDD VSS VDDARRAY! VSS!"
  - "heichips25_core.fabric_wrapper.sram0_1 VDD VSS VDD! VSS!"
  - "heichips25_core.fabric_wrapper.sram0_1 VDD VSS VDDARRAY! VSS!"
