name: CI

# Events that trigger the workflow
on:
  # Runs on all pushes to branches
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  # Runs on all PRs
  pull_request:
  # Manual Dispatch
  workflow_dispatch:

concurrency:
  # Behavior:
  # - Group all pull requests: latest push cancels previous ones
  # - Group all branches:
  #   - If main/version- branches: run serially
  #   - Else, latest push cancels previous ones
  group: >
    ${{
      (github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number)) ||
      (github.event_name == 'push' && format('branch-{0}', github.ref_name)) ||
      ''
    }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || !(startsWith(github.ref_name, 'version-') || github.ref_name == 'main' || github.ref_name == 'dev') }}

jobs:
  tiles:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        pdk: [ihp-sg13g2]
        tile_library: [classic]
    name: Tiles (${{ matrix.tile_library }}/${{ matrix.pdk }})
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Nix
        uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          nix_cache_domain: ${{ vars.NIX_CACHE }}
          nix_public_key: ${{ vars.NIX_PUBLIC_KEY }}
      - name: Build with Nix
        uses: ./.github/actions/build_nix
        with:
          nix_system: x86_64-linux
          derivation: github:mole99/librelane_plugin_fabulous
      - name: Get the tile library hash
        run: |
          echo "TILE_LIBRARY_SHORT_HASH=$(git rev-parse --short HEAD:ip/fabulous-tiles)" >> $GITHUB_ENV
      - name: Cache the tiles
        uses: actions/cache@v5
        id: cache
        with:
          path: ip/fabulous-tiles/tiles
          key: cache-tiles-${{ matrix.tile_library }}-${{ matrix.pdk }}-${{ env.TILE_LIBRARY_SHORT_HASH }}
      - name: Implement the tiles
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd ip/fabulous-tiles/; PDK=${{ matrix.pdk }} TILE_LIBRARY=${{ matrix.tile_library }} nix develop --command make all

  chip:
    runs-on: ubuntu-24.04
    needs: [tiles]
    strategy:
      matrix:
        pdk: [ihp-sg13g2]
        fabrics: [classic_fabric_heichips25]
    name: Build the Chip
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Clone the PDK
        run: |
          make clone-pdk
      - name: Setup Nix
        uses: ./.github/actions/setup_nix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          nix_cache_domain: ${{ vars.NIX_CACHE }}
          nix_public_key: ${{ vars.NIX_PUBLIC_KEY }}
      - name: Build with Nix
        uses: ./.github/actions/build_nix
        with:
          nix_system: x86_64-linux
      - name: Check Nix
        run: |
          sudo du -hs /nix/store/* | sort -h | tail -n 10
          sudo tree /nix/store/*-librelane || true
      - name: Get the tile library name and hash
        run: |
          echo "TILE_LIBRARY=$(echo "${{ matrix.fabrics }}" | cut -d'_' -f1)" >> $GITHUB_ENV
          echo "TILE_LIBRARY_SHORT_HASH=$(git rev-parse --short HEAD:ip/fabulous-tiles)" >> $GITHUB_ENV
      - name: Restore the tiles
        uses: actions/cache/restore@v5
        with:
          path: ip/fabulous-tiles/tiles
          key: cache-tiles-${{ env.TILE_LIBRARY }}-${{ matrix.pdk }}-${{ env.TILE_LIBRARY_SHORT_HASH }}
          fail-on-cache-miss: true
      - name: Stitch the tiles
        run: |
          PDK=${{ matrix.pdk }} nix develop --command make ${{ matrix.fabrics }}
      - name: Upload Macro Folder
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.fabrics }}_${{ matrix.pdk }}
          path: fabrics/${{ matrix.fabrics }}/macro/${{ matrix.pdk }}/
          include-hidden-files: true
      - name: Implement the User Designs
        run: |
          cd user_designs; PDK=${{ matrix.pdk }} TILE_LIBRARY=${{ env.TILE_LIBRARY }} FABRIC=${{ matrix.fabrics }} nix develop --command make all
      - name: Simulate the Fabric RTL (Emulation)
        run: |
          nix develop --command make sim-fabric-emulation
      - name: Simulate the Fabric RTL (Simulation)
        run: |
          nix develop --command make sim-fabric
        - name: Simulate the Fabric GL (Simulation)
        run: |
          nix develop --command make sim-fabric-gl
      - name: Implement the Chip
        if: success() || failure()
        run: |
          nix develop --command make librelane-nodrc
          nix develop --command make render-image
      - name: Create summary
        if: success() || failure()
        run: |
          echo "# Manufacturability" >> $GITHUB_STEP_SUMMARY
          cat librelane/runs/*/*-misc-reportmanufacturability/manufacturability.rpt >> $GITHUB_STEP_SUMMARY
      - name: Upload GDS
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: final_gds
          path: final/gds/*
      - name: Upload image
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: heichips25_image
          path: |
            img/heichips25_top_white.png
            img/heichips25_top_white_small.png
            img/heichips25_top_black.png
            img/heichips25_top_black_small.png
      - name: Simulate the FPGA RTL (Emulation)
        run: |
          nix develop --command make sim-top-emulation
      - name: Simulate the FPGA RTL (Simulation)
        run: |
          nix develop --command make sim-top
      - name: Simulate the FPGA GL (Simulation)
        run: |
          nix develop --command make sim-top-gl
